
name: First Github Action Pipeline

run-name: Deploy by @${{ github.actor }}

on:

    workflow_dispatch:
        inputs:
            user_name:
                description: 'What is your user name ?'
                required: true
                type: string
    schedule:
        - cron: '*/6 * * * *'

jobs:
    print-username:
        name: name printing
        runs-on: ubuntu-latest
        steps:
        - name: Print the input name to STDOUT
          run: |
            echo The username is ${{ inputs.user_name || 'Guy you no try jare.....mtcheeeew'}}  
            echo '${{ github.workflow }} - ${{ github.event_name }} '
            # echo '${{ toJSON(github) }}'
