
name: First Github Action Pipeline

run-name: Deploy by @${{ github.actor }}

on:
    push:

    workflow_dispatch:
        inputs:
            user_name:
                description: 'What is your user name ?'
                required: true
                type: string
    schedule:
        - cron: '*/2 * * * *'

jobs:
    print-username:
        name: name printing
        runs-on: ubuntu-latest
        steps:
        - name: Print the input name to STDOUT
          run: echo The username is ${{ inputs.user_name || 'Guy you no try jare.....mtcheeeew'}} ${{github.event}}
